

name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
      - name: Scripts
        run: |
         docker build -t app .
         docker login -u venkateswararaju -p dckr_pat_d1Gif6ieg_v32FyLPKU4HlWOLYM
         docker tag app venkateswararaju/test
         docker push venkateswararaju/test
